AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a simple EC2 instance

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 Key Pair

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-04ea4e8270c27626c
      KeyName: !Ref KeyName

      Tags:
        - Key: Name
          Value: ohio-passkey

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: Public IP Address
    Value: !GetAtt MyEC2Instance.PublicIp
